-- 1. Male employees with net salary >= 8000 ordered by seniority
SELECT 
    EMPLOYEE_NUMBER,
    FIRST_NAME,
    LAST_NAME,
    DATEDIFF(YEAR, BIRTH_DATE, GETDATE()) AS Age,
    DATEDIFF(YEAR, HIRE_DATE, GETDATE()) AS Seniority
FROM EMPLOYEES
WHERE TITLE = 'Mr'
  AND (SALARY + ISNULL(COMMISSION, 0)) >= 8000
ORDER BY Seniority DESC;









-- 2. Products meeting conditions C1–C5
SELECT 
    PRODUCT_REF,
    PRODUCT_NAME,
    SUPPLIER_NUMBER,
    UNITS_ON_ORDER,
    UNIT_PRICE
FROM PRODUCTS
WHERE QUANTITY LIKE '%bottle%'
  AND SUBSTRING(PRODUCT_NAME, 3, 1) IN ('t', 'T')
  AND SUPPLIER_NUMBER IN (1, 2, 3)
  AND UNIT_PRICE BETWEEN 70 AND 200
  AND UNITS_ON_ORDER IS NOT NULL;



-- 3. Customers in the same region as supplier 1
  SELECT *
FROM CUSTOMERS C
WHERE EXISTS (
    SELECT 1
    FROM SUPPLIERS S
    WHERE S.SUPPLIER_NUMBER = 1
      AND S.COUNTRY = C.COUNTRY
      AND S.CITY = C.CITY
      AND RIGHT(S.POSTAL_CODE, 3) = RIGHT(C.POSTAL_CODE, 3)
);



-- 4. Discount rate and application note
SELECT 
    OD.ORDER_NUMBER,
    CASE
        WHEN SUM(UNIT_PRICE * QUANTITY) BETWEEN 0 AND 2000 THEN '0%'
        WHEN SUM(UNIT_PRICE * QUANTITY) BETWEEN 2001 AND 10000 THEN '5%'
        WHEN SUM(UNIT_PRICE * QUANTITY) BETWEEN 10001 AND 40000 THEN '10%'
        WHEN SUM(UNIT_PRICE * QUANTITY) BETWEEN 40001 AND 80000 THEN '15%'
        ELSE '20%'
    END AS New_Discount_Rate,
    CASE
        WHEN OD.ORDER_NUMBER BETWEEN 10000 AND 10999 
        THEN 'apply old discount rate'
        ELSE 'apply new discount rate'
    END AS Discount_Application_Note
FROM ORDER_DETAILS OD
WHERE OD.ORDER_NUMBER BETWEEN 10998 AND 11003
GROUP BY OD.ORDER_NUMBER;






-- 5. Suppliers of beverage products
SELECT DISTINCT
    S.SUPPLIER_NUMBER,
    S.COMPANY,
    S.ADDRESS,
    S.PHONE
FROM SUPPLIERS S
JOIN PRODUCTS P ON S.SUPPLIER_NUMBER = P.SUPPLIER_NUMBER
JOIN CATEGORIES C ON P.CATEGORY_CODE = C.CATEGORY_CODE
WHERE C.CATEGORY_NAME = 'Beverages';




-- 6. Berlin customers who ordered at most one dessert product
SELECT C.CUSTOMER_CODE
FROM CUSTOMERS C
LEFT JOIN ORDERS O ON C.CUSTOMER_CODE = O.CUSTOMER_CODE
LEFT JOIN ORDER_DETAILS OD ON O.ORDER_NUMBER = OD.ORDER_NUMBER
LEFT JOIN PRODUCTS P ON OD.PRODUCT_REF = P.PRODUCT_REF
LEFT JOIN CATEGORIES CA ON P.CATEGORY_CODE = CA.CATEGORY_CODE
WHERE C.CITY = 'Berlin'
  AND CA.CATEGORY_NAME = 'Desserts'
GROUP BY C.CUSTOMER_CODE
HAVING COUNT(DISTINCT P.PRODUCT_REF) <= 1;




-- 7. French customers and total orders every Monday in April 1998
SELECT 
    C.CUSTOMER_CODE,
    C.COMPANY,
    C.PHONE,
    ISNULL(SUM(OD.UNIT_PRICE * OD.QUANTITY), 0) AS Total_Amount,
    C.COUNTRY
FROM CUSTOMERS C
LEFT JOIN ORDERS O ON C.CUSTOMER_CODE = O.CUSTOMER_CODE
LEFT JOIN ORDER_DETAILS OD ON O.ORDER_NUMBER = OD.ORDER_NUMBER
WHERE C.COUNTRY = 'France'
  AND (O.ORDER_DATE IS NULL OR
      (DATENAME(WEEKDAY, O.ORDER_DATE) = 'Monday'
       AND MONTH(O.ORDER_DATE) = 4
       AND YEAR(O.ORDER_DATE) = 1998))
GROUP BY C.CUSTOMER_CODE, C.COMPANY, C.PHONE, C.COUNTRY;


-- 8. Customers who ordered all products
SELECT 
    C.CUSTOMER_CODE,
    C.COMPANY,
    C.PHONE
FROM CUSTOMERS C
WHERE NOT EXISTS (
    SELECT P.PRODUCT_REF
    FROM PRODUCTS P
    WHERE NOT EXISTS (
        SELECT 1
        FROM ORDERS O
        JOIN ORDER_DETAILS OD ON O.ORDER_NUMBER = OD.ORDER_NUMBER
        WHERE O.CUSTOMER_CODE = C.CUSTOMER_CODE
          AND OD.PRODUCT_REF = P.PRODUCT_REF
    )
);


-- 9. Number of orders per French customer
SELECT 
    C.CUSTOMER_CODE,
    COUNT(O.ORDER_NUMBER) AS Number_Of_Orders
FROM CUSTOMERS C
LEFT JOIN ORDERS O ON C.CUSTOMER_CODE = O.CUSTOMER_CODE
WHERE C.COUNTRY = 'France'
GROUP BY C.CUSTOMER_CODE;



-- 10. Orders in 1996 vs 1997 and the difference
SELECT
    SUM(CASE WHEN YEAR(ORDER_DATE) = 1996 THEN 1 ELSE 0 END) AS Orders_1996,
    SUM(CASE WHEN YEAR(ORDER_DATE) = 1997 THEN 1 ELSE 0 END) AS Orders_1997,
    SUM(CASE WHEN YEAR(ORDER_DATE) = 1997 THEN 1 ELSE 0 END) -
    SUM(CASE WHEN YEAR(ORDER_DATE) = 1996 THEN 1 ELSE 0 END) AS Difference
FROM ORDERS;
